### ISSUE TITLE
Problem with json_encode in solr:delete command

### ISSUE THREAD

**Issue by jschultze** [NatLibFi/RecordManager#152]
When running the command

`./console solr:delete  <source>`

the following JSON is generated and send to the Solr index:

`{ "delete": { "query": "id:"<source>".*" } }`

This results in an error, as`json_encode()` adds quotation marks around <source>, which invalidates the generated JSON. The JSON send to the Solr index should be:

`{ "delete": { "query": "id:<source>.*" } }`

Would it be save to remove the `json_encode()` in this code?

```
$this->solrRequest(
    '{ "delete": { "query": "id:' . json_encode($sourceId) . '.*" } }'
);
```

**Comment by EreMaijala** [comment]
@jschultze Thanks for reporting the issue. It should now be fixed by the referenced commit.

**Comment by jschultze** [comment]
Great, thanks!
