### ISSUE TITLE
New Option for harvest to not pull deleted

### ISSUE THREAD

**Issue by bpalme** [NatLibFi/RecordManager#84]
Hi,
It would be nice to add in an option (or possibly an automatic configuration when reharvesting?) to the SierraAPI harvester that does not pull deleted records.  When we do a full reharvest, we have to churn through 300K deleted records.  Someday I'll try to do a PR.

Thanks,
Brent

**Comment by EreMaijala** [comment]
I've added automatic skipping of deleted records during reharvest. I hope this helps!
