### ISSUE TITLE
Turning on other harvesters

### ISSUE THREAD

**Issue by bpalme** [NatLibFi/RecordManager#85]
Hi,
We use a different harvester for Overdrive that overrides the AbstractBase.  In order to use it, I overrode the harvest controller and then changed the harvest.php script to point to my controller.  It seems like maybe there is a better way to do that for long-term maintenance. For Sierra, there is a "type" that switches on the SierraAPI Harvester.  Maybe some other configuration that can switch on my Overdrive one… specifying the class maybe? I haven't figured it out, but I thought I'd mention in case you have a good idea.

**Comment by EreMaijala** [comment]
See #89. :)

**Comment by bpalme** [comment]
Thank you!

**Comment by EreMaijala** [comment]
dev version now supports custom modules and uses Laminas plugin managers. This has brief documentation in README.md. I'll be adding more docs to the wiki.
